import React from 'react';
import Footer from './Footer'

const Rules = () => {
    return (
        <>
            <div className="row">
                <div className="col-8">
                    <div className="box box-3">
                        <h1>ZZZZZZZZZZZ</h1>
                        <div className='lorem'>Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>
                        <div className='lorem'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi ipsum perspiciatis nam accusamus neque, molestiae impedit explicabo sunt, tempora sequi accusantium enim est delectus ducimus provident maiores quod numquam ratione dicta eveniet quidem iusto! Quidem nostrum id deleniti magni consequatur, nisi quia am eaque culpa corrupti. Sequi amet, illum, accusantium error magni possimus et non ut, quaerat molestias pariatur alias assumenda vero consequatur qui aspernatur doloremque unde praesentium! Veritatis libero aliquid repudiandae, ipsa ullam hic veniam ratione quas obcaecati sapiente placeat voluptate molestias animi reprehenderit itaque pariatur necessitatibus dolore illum explicabo! Iure corrupti porro nam natus possimus ut ab, inventore perspiciatis est nesciunt cum explicabo aut reprehenderit odio ex, a iusto expedita perferendis sunt.Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid veritatis perspiciatis aspernatur quisquam ex atque reprehenderit est repellat! Neque, placeat autem. Tenetur illo debitis placeat eos blanditiis molestias corrupti. Quisquam sapiente in, labore maxime praesentium ratione magni maiores animi quaerat quae ad laborum vel officia nihil architecto dolorum dolores accusamus non quod. Architecto maxime totam blanditiis ut libero deserunt dolorem doloribus corrupti facere quasi dolor sint voluptas dolorum perferendis nam velit, dignissimos officia, recusandae quo nobis aspernatur cupiditate excepturi placeat quisquam. Explicabo aperiam eveniet at nemo quaerat quae. Maxime beatae possimus molestiae aperiam reprehenderit nobis mollitia aliquam illum cumque ipsam.</div>

                    </div>
                </div>
                <div className="col-4">
                    <div className="box box-4">
                        <div className='slogan'>Bądźmy w kontakcie</div>
                        <div className="line"></div>
                        <div className="line"></div>

                        <div className='content-text-right'>Odpowiem na wszystkie Państwa pytania i wyjaśnię wątpliwości</div>
                        <div className='icon'><i className="fas fa-phone"></i>tel. 698 691 198</div>
                        <div className='icon'><i className="fas fa-at"></i>iwonakotwicka@wp.pl</div>
                        <div className='icon'><i className="fas fa-map-marked"></i>44-200 Rybnik, Wodna 65</div>
                        <div className="content-text-right">Adres do korespondencji. Chętnie się z Państwem spotkam po umówieniu terminu. Zapraszam.</div>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}
export default Rules